const categories = [
  { id: 1, name: "Молоко, сыр, яйцо" },
  { id: 2, name: "Напитки" },
  { id: 3, name: "Бакалея" },
  { id: 4, name: "Непродовольственные товары" },
  { id: 5, name: "Хлеб" },
  { id: 6, name: "Кондитерские изделия" },
  { id: 7, name: "Здоровое питание" },
  { id: 8, name: "Детское питание" },
  { id: 5, name: "Фрукты и овощи" },
  { id: 6, name: "Чай, кофе" },
  { id: 7, name: "Зоотовары" },
  { id: 8, name: "Мясо, птица, колбаса" },
  { id: 9, name: "Замороженные продукты" },
];
const category = [
  {
    id: 1,
    name: "Молоко, сыр, яйцо",
    category: "Milk",
    image: "../images/pages/category/img.png",
  },
  {
    id: 2,
    category: "bread",
    name: "Хлеб",
    image: "../images/pages/category/bread.png",
  },
  {
    id: 3,
    category: "healthy-food",
    name: "Фрукты и овощи",
    image: "../images/pages/category/fructis.png",
  },
  {
    id: 4,
    category: "frozen-food",
    name: "Замороженные продукты",
    image: "../images/pages/category/vegetables.png",
  },
  {
    id: 5,
    category: "Bevarage",
    name: "Напитки",
    image: "../images/pages/category/waters.png",
  },
  {
    id: 6,
    category: "confectionery",
    name: "Кондитерские изделия",
    image: "../images/pages/category/sweet.png",
  },
  {
    id: 7,
    category: "Tea-coffee",
    name: "Чай, кофе",
    image: "../images/pages/category/tea.png",
  },
  {
    id: 8,
    category: "Flour",
    name: "Бакалея",
    image: "../images/pages/category/makaron.png",
  },
  {
    id: 9,
    category: "Healthy-eating",
    name: "Здоровое пита",
    image: "../images/pages/category/cucember.png",
  },
  {
    id: 10,
    category: "Pet-supliers",
    name: "Здоровое питание",
    image: "../images/pages/category/animals.png",
  },
  {
    id: 11,
    category: "Baby-food",
    name: "Детское питание",
    image: "../images/pages/category/childfructs.png",
  },
  {
    id: 12,
    category: "Sausage",
    name: "Мясо, птица, колбаса",
    image: "../images/pages/category/meat.png",
  },
  {
    id: 13,
    category: "Non-food",
    name: "Непродовольственные товары",
    image: "../images/pages/category/cleaners.png",
  },
];
